name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.8.1
    with:
      env: '["py310", "py311", "py312"]'
